### ISSUE TITLE
A maybe more polished version of the same project.

### ISSUE THREAD

**Issue by kunathj** [Cryoris/twexit#1]
Hi @Cryoris

I recently took some time to polish-up [my version](https://github.com/kunathj/Brexit-Twitter ) of our old Brexit analyis.

I tried to improve the code readability in some places and cleaned up the data files a bit.
I fixed some tweet-parsing errors that were introduced when we converted our tweets to .csv.

Probably most notable, I removed quite some redundant tweets from our big data files.
Maybe you can have a look at that rewrite.

Cheers,

Jonas

**Comment by Cryoris** [comment]
Nice! I definitely will -- even your README was polished-up, I like it 🙂

**Comment by Cryoris** [comment]
Maybe we can merge these then

**Comment by kunathj** [comment]
Happy to hear you're interested.
I invited you to join on my project as a collaborator. If you prefer creating a stand-alone organization for this one repository, feel free to go along.
